<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tu direccin de correo electrnico temporal_mail</name>
   <tag></tag>
   <elementGuidId>bb765abe-5225-4c87-9658-9b8afed60677</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b93691f-b5aa-4153-b5c2-68cc7743f298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mail</value>
      <webElementGuid>5f5de054-33fc-4819-9441-ad4a81aca510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4a51df3d-4398-4939-9063-8716adeaf6be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>select(this);</value>
      <webElementGuid>b35f1dd5-3d5e-4fcf-b418-81a61dcd74a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Tu dirección de correo electrónico temporal</value>
      <webElementGuid>2bde9472-e4bc-4565-8acd-c37244197644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>f7366cd1-f4f8-42b4-85d8-f65bae17cd3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Cargando</value>
      <webElementGuid>cf76d4a7-5ac8-4c7a-bf80-dd3c27fa827e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>emailbox-input opentip</value>
      <webElementGuid>ba0bddbb-ca83-44a9-a399-3368e2476802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip961446</value>
      <webElementGuid>586a9d17-2811-4605-8fdc-5bff0c9771d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mail&quot;)</value>
      <webElementGuid>8f41a152-3482-43f7-9da2-7c3eced37ca1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mail']</value>
      <webElementGuid>3b692f36-46a0-4457-a219-14930b694737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='tm-body']/div/div/div/div[2]/div/form/div/div/input</value>
      <webElementGuid>427e4db9-ad89-445d-ae70-bd2ed6d3c6dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3944bb53-fc62-4f40-b91d-3974be8c1bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mail' and @type = 'text']</value>
      <webElementGuid>214e3451-a491-47fa-a1de-29629e2892f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
