<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tu direccin de correo electrnico temporal_mail</name>
   <tag></tag>
   <elementGuidId>8283802c-ab8f-40fd-8b32-ec72f8ba6c31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mail' and @class='emailbox-input opentip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53eacb6a-87d1-4ad0-86c6-60fcf2a28f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mail</value>
      <webElementGuid>727bcfd6-9e88-4f66-9a5b-eb17a8970847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d25d9566-32ec-4097-a475-2335b96e9939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>select(this);</value>
      <webElementGuid>de3b6cd1-f206-4e6c-9903-06324531dcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Tu dirección de correo electrónico temporal</value>
      <webElementGuid>72b14d2f-c71d-4fa7-a4b2-280aca358642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>0198d1eb-9367-4850-b46d-d666eb37d31b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Cargando</value>
      <webElementGuid>4715ad36-60ce-4fa6-a7dc-d62adbdc66a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>emailbox-input opentip</value>
      <webElementGuid>c93db18b-383a-4f38-a5b2-847d64a150a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip817676</value>
      <webElementGuid>34f003e4-b54c-4754-b340-c8e0d59597b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mail&quot;)</value>
      <webElementGuid>284b37f1-37bc-48c4-89a1-e00c73a4f9c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mail']</value>
      <webElementGuid>8cccf4b0-da0b-4b75-9da0-a033168cc965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='tm-body']/div/div/div/div[2]/div/form/div/div/input</value>
      <webElementGuid>c42d9b3d-b532-4cb3-9c24-69c836fdd58f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>265fa50e-b26c-44d7-810f-9006234724db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mail' and @type = 'text']</value>
      <webElementGuid>b2954acf-e9a8-4d3d-b6af-c24264e64106</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
