<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Precio De menor a mayor</name>
   <tag></tag>
   <elementGuidId>3a28ec6a-ffec-4f59-be03-9687ef265a56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#s-result-sort-select_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='s-result-sort-select_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b6733921-f2e9-48bb-a1ad-680d38cc7e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f3c0bfc8-31c3-4af4-b893-af98a123235d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>0747fb48-5fde-419a-9059-7b87fa04231a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>708259f3-5d62-42b0-b785-65ded3acda65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>{&quot;stringVal&quot;:&quot;price-asc-rank&quot;}</value>
      <webElementGuid>fd18d2fe-426e-44be-bdd5-7d751ce376b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>s-result-sort-select_1</value>
      <webElementGuid>108858df-ad84-401b-8afc-47fb693c0f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-link</value>
      <webElementGuid>d53dedda-27cc-45ea-a329-b7d41e1e4d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Precio: De menor a mayor</value>
      <webElementGuid>b7db078b-662c-4af2-933b-871d23af387f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s-result-sort-select_1&quot;)</value>
      <webElementGuid>38c60d1a-a520-4450-8dd2-25ff85d57bb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='s-result-sort-select_1']</value>
      <webElementGuid>30a1b330-81c9-4e1b-a8c9-7dc8eed94f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-popover-2']/div/div/ul/li[2]/a</value>
      <webElementGuid>390ee9de-8a97-494e-9f68-5a523a219282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Precio: De menor a mayor')]</value>
      <webElementGuid>a95049f6-53da-402f-8f29-0691fd4f5d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[19]</value>
      <webElementGuid>a813ddca-79c8-457f-bada-fc172abf3630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/ul/li[2]/a</value>
      <webElementGuid>414f2e0a-0c5a-407b-ae4a-e0a88bae6b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 's-result-sort-select_1' and (text() = 'Precio: De menor a mayor' or . = 'Precio: De menor a mayor')]</value>
      <webElementGuid>ffb413e2-bdb3-4aa7-9731-1734302563a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
